### ISSUE TITLE
KeyError: 'Non-existent config key: transaction'

### ISSUE THREAD

**Issue by BITNEO** [snap-stanford/roland#11]
Traceback (most recent call last):
  File "/home/roland-master/run/main.py", line 185, in <module>
    cfg.merge_from_file(args.cfg_file)
  File "/home/anaconda3/envs/torch/lib/python3.9/site-packages/yacs/config.py", line 213, in merge_from_file
    self.merge_from_other_cfg(cfg)
  File "/home/anaconda3/envs/torch/lib/python3.9/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/home/anaconda3/envs/torch/lib/python3.9/site-packages/yacs/config.py", line 473, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: transaction'
It seems some keys (e.g. transaction) in .yaml configuation files are not supported ?

**Comment by TianyuDu** [comment]
Thanks for your feedback! Could you please provide the command (e.g., `python ....`) you ran so that I can replicate and investigate into this issue?
