### ISSUE TITLE
Error when running .sh files

### ISSUE THREAD

**Issue by aravinda-1402** [snap-stanford/roland#5]
(roland) aravinda@aravinda-1402:/media/aravinda/New Volume1/roland-master/run$ python3 main.py --cfg './roland_example.yaml' --repeat 1 --override_data_dir '/media/aravinda/New Volume1/roland-master/roland_public_data' --override_remark 'roland_example'
Traceback (most recent call last):
  File "/media/aravinda/New Volume1/roland-master/run/main.py", line 12, in <module>
    from graphgym.logger import setup_printing, create_logger
  File "/media/aravinda/New Volume1/roland-master/graphgym/logger.py", line 12, in <module>
    from tensorboardX import SummaryWriter
  File "/home/aravinda/anaconda3/envs/roland/lib/python3.9/site-packages/tensorboardX/__init__.py", line 5, in <module>
    from .torchvis import TorchVis
  File "/home/aravinda/anaconda3/envs/roland/lib/python3.9/site-packages/tensorboardX/torchvis.py", line 11, in <module>
    from .writer import SummaryWriter
  File "/home/aravinda/anaconda3/envs/roland/lib/python3.9/site-packages/tensorboardX/writer.py", line 17, in <module>
    from .comet_utils import CometLogger
  File "/home/aravinda/anaconda3/envs/roland/lib/python3.9/site-packages/tensorboardX/comet_utils.py", line 5, in <module>
    from google.protobuf.json_format import MessageToJson
  File "/home/aravinda/anaconda3/envs/roland/lib/python3.9/site-packages/google/protobuf/json_format.py", line 54, in <module>
    from google.protobuf.internal import type_checkers
  File "/home/aravinda/anaconda3/envs/roland/lib/python3.9/site-packages/google/protobuf/internal/type_checkers.py", line 51, in <module>
    from google.protobuf.internal import decoder
  File "/home/aravinda/anaconda3/envs/roland/lib/python3.9/site-packages/google/protobuf/internal/decoder.py", line 87, in <module>
    from google.protobuf.internal import encoder
  File "/home/aravinda/anaconda3/envs/roland/lib/python3.9/site-packages/google/protobuf/internal/encoder.py", line 71, in <module>
    from google.protobuf.internal import wire_format
  File "/home/aravinda/anaconda3/envs/roland/lib/python3.9/site-packages/google/protobuf/internal/wire_format.py", line 36, in <module>
    from google.protobuf import descriptor
  File "/home/aravinda/anaconda3/envs/roland/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 40, in <module>
    from google.protobuf.internal import api_implementation
  File "/home/aravinda/anaconda3/envs/roland/lib/python3.9/site-packages/google/protobuf/internal/api_implementation.py", line 104, in <module>
    from google.protobuf.pyext import _message
TypeError: bases must be types

**Comment by aravinda-1402** [comment]
Reinstalled protobuf, and it worked.

**Comment by TianyuDu** [comment]
Sorry for the late reply; glad that you figured it out!

**Comment by xirong312** [comment]
I meet the same error,I try reinstall protobuf but it desn't work.so which version of protobuf is needed?

**Comment by TianyuDu** [comment]
Can you try the version `protobuf==4.21.1`?

**Comment by ysinwell** [comment]
> Can you try the version `protobuf==4.21.1`?

In fact,I meet the same question with the issue while I create conda env by provided yml file and I make sure use   `protobuf==4.21.1`
